export 'package:widgets_app/presentation/screens/animated/animated_screem.dart';
export 'package:widgets_app/presentation/screens/app_tutorial/app_tutorial.dart';
export 'package:widgets_app/presentation/screens/Buttons/buttons_screen.dart';
export 'package:widgets_app/presentation/screens/Cards/cards_screen.dart';
export 'package:widgets_app/presentation/screens/Home/home_screen.dart';
export 'package:widgets_app/presentation/screens/infinite_scroll/infinite_scroll_screen.dart';
export 'package:widgets_app/presentation/screens/progress/progress_screen.dart';
export 'package:widgets_app/presentation/screens/snackbar/snacbar_screen.dart';
export 'package:widgets_app/presentation/screens/ui_controls/ui_controls_screen.dart';
